# This is a basic workflow to help you get started with Actions

name: CICD_develop_DEV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  APP_DIR: SDR-WebApp
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DEV
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Use Node 16.x
        uses: actions/setup-node@v4
        with:
          # The node.js version to use
          node-version: '16'
          cache: 'npm'

      - name: Install Dependencies
        working-directory: ${{ env.APP_DIR }}
        run: npm ci
    
      - name: Install Chrome (for Karma)
        uses: browser-actions/setup-chrome@v2
        id: setup-chrome
        
      - name: Run Unit Tests (Karma/Jasmine)
        working-directory: ${{ env.APP_DIR }}
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.crhome-path }}
        run: npx ng test --reporters junit --watch=false --browsers=ChromeHeadless

      - name: Publish Unit Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: ${{ env.APP_DIR }}/testresults/junit/**/*.xml

      - name: Build App
        working-directory: ${{ env.APP_DIR }}
        run: npx ng build --configuration production
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ${{ env.APP_DIR }}/dist
          if-no-files-found: error
